### ISSUE TITLE
 ...z/scripts/dzVents/generated_scripts/Soleil2 dz timer.lua:166: ')' expected near ','

### ISSUE THREAD

**Issue by deennoo** [russandol-sarl/dz-solarData#2]
Hi there,

I'm using your script since a longtime now.
 I 'm facing an error with last version

` Error: dzVents: Error: (3.0.4) error loading module 'Soleil2 dz timer' from file '/home/nico/domoticz/scripts/dzVents/generated_scripts/Soleil2 dz timer.lua':
2020-05-09 14:37:11.183 ...z/scripts/dzVents/generated_scripts/Soleil2 dz timer.lua:166: ')' expected near ','`

**Comment by oredin** [comment]
Hi,

Thanks for reporting this error ! It was just a little typo when I changed Math.pow to the recommended operator in LUA.

I just fix it. You can update the code and it should work again !

NB : I can't test the correction since I don't have my DZ around at the moment. Let me know if there's another error.

Regards

**Comment by deennoo** [comment]
All is good now.
